[package]
name = "pathology"
version = "1.0.0"
edition = "2021"
authors = ["Jackson Zamorano"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
